# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.cache/wt [current_project]
set_property parent.project_path E:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo e:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.srcs/sources_1/new/triggerGenerator.vhd
  E:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.srcs/sources_1/new/echo_period.vhd
  E:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.srcs/sources_1/new/clk_divider_100KHz.vhd
  E:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.srcs/sources_1/new/ultrasonic.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files E:/FPGA/senzor_ultrasonic_Sabau/senzor_ultrasonic_Sabau.srcs/constrs_1/new/constr.xdc]


synth_design -top ultrasonic -part xc7z010clg400-1


write_checkpoint -force -noxdef ultrasonic.dcp

catch { report_utilization -file ultrasonic_utilization_synth.rpt -pb ultrasonic_utilization_synth.pb }
